DROP DATABASE IF EXISTS BLOG;

CREATE DATABASE BLOG;

USE BLOG;

CREATE TABLE USUARIO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA CHAR(60) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ATIVO TINYINT NOT NULL DEFAULT '0',
    ADM TINYINT NOT NULL DEFAULT '0',
    PRIMARY KEY(ID)
);

CREATE TABLE POST(
    ID INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    TEXTO TEXT NOT NULL,
    USUARIO_ID INT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_POSTAGEM DATETIME NOT NULL,
    PRIMARY KEY(ID),
    KEY FK_POST_USUARIO_IDX (USUARIO_ID),
    CONSTRAINT FK_USUARIOPOST FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);